import Feed from "components/Feed";
import Head from "next/head";

export default function Home(): React.ReactElement {
  return (
    <>
      <Head>
        <title>Instagram 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <Feed />
    </>
  );
}
