import SplashScreen from "components/shared/SplashScreen";
import Head from "next/head";

export default function Home() {
  const isLoading = true;
  if (isLoading) return <SplashScreen />;
  return (
    <>
      <Head>
        <title>Instagram 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/icons/favicon.png" />
      </Head>
      <p className="text-amber-500">This is the landing page</p>
    </>
  );
}
